apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"meta.helm.sh/release-name":"v1","meta.helm.sh/release-namespace":"default"},"creationTimestamp":"2024-04-18T18:18:31Z","labels":{"app.kubernetes.io/instance":"v1","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"10.4.1","helm.sh/chart":"grafana-7.3.9"},"name":"v1-grafana","namespace":"default","resourceVersion":"3071305","uid":"090b7757-9ece-44ce-815e-4cd564a64e25"},"spec":{"clusterIP":"10.0.191.171","clusterIPs":["10.0.191.171"],"externalTrafficPolicy":"Cluster","internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"service","nodePort":30498,"port":3000,"protocol":"TCP","targetPort":3000}],"selector":{"app.kubernetes.io/instance":"v1","app.kubernetes.io/name":"grafana"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
    meta.helm.sh/release-name: v1
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-04-18T18:18:31Z"
  labels:
    app.kubernetes.io/instance: v1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.4.1
    helm.sh/chart: grafana-7.3.9
  name: v1-grafana
  namespace: default
  resourceVersion: "3072542"
  uid: 090b7757-9ece-44ce-815e-4cd564a64e25
spec:
  clusterIP: 10.0.191.171
  clusterIPs:
  - 10.0.191.171
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: service
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: v1
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}